### ISSUE TITLE
IP device "dies" after a few minutes?

### ISSUE THREAD

**Issue by WhittlesJr** [Frozenlock/bacure#19]
I feel like we've talked about this before, but I can't find the conversation. 

My IP-based local device will just stop sending requests after a few minutes. For example, I'll run 

```
(bacure.remote-device/find-remote-devices 100203 {:min-range nil, :max-range nil})
```
but I see nothing in Wireshark. My request never went out the door. 

If I kill and re-create my local device, things start working happily again for a few minutes.

I can try to add more detail, but have you experienced anything like this, or is it just me?

**Comment by Frozenlock** [comment]
Doesn't ring any bell.

Is it with MS/TP?

**Comment by WhittlesJr** [comment]
It is apparently both IP and MS/TP. Requests just stop going out after about 4 minutes.

**Comment by WhittlesJr** [comment]
wait, it might be my fault... hold on

**Comment by WhittlesJr** [comment]
Yep, my fault. I was disabling comms at some point (bacure.local-device/disable-communications!). No wonder it wouldn't communicate!

**Comment by Frozenlock** [comment]
No problem.
Btw, any idea when you might be able to do the MS/TP tests?
I'm afraid of changing things without those.

**Comment by WhittlesJr** [comment]
Tell you what... I will try to implement one every week-day starting today.

**Comment by WhittlesJr** [comment]
Although, without Midje, I'm not sure how best to mock out certain things...
