### ISSUE TITLE
Insecure HTTP repo

### ISSUE THREAD

**Issue by WhittlesJr** [Frozenlock/bacure#21]
I don't think it's [BACnet4J](https://github.com/infiniteautomation/BACnet4J/issues/20) anymore, at least not if you use 4.1.5... I need to dig a bit more to see what it is. 

We should also update to 4.1.5 to get the HTTPS fix. 

But I also can't build bacure out-of-the-box without `lein install`-ing the HEAD of clj-serial (because it [needs to cut a release](https://github.com/peterschwarz/clj-serial/issues/12).

But even with 4.1.5 and clj-serial's HEAD, I still get `Insecure HTTP repo`.

**Comment by WhittlesJr** [comment]
I think it's still purejavacomm, but I can't figure out why... I thought that was fixed in clj-serial

**Comment by WhittlesJr** [comment]
Er, no, it's sero-scheduler:

```
HTTP Wagon get: lohbihler/sero-scheduler/maven-metadata.xml from #object[java.io.File 0x49caa0b /home/alexj/.m2/repository/lohbihler/sero-scheduler/maven-metadata-jcenter.xml.part]                             
Retrieving lohbihler/sero-scheduler/1.1.0/sero-scheduler-1.1.0.pom from ias-releases                                                       
HTTP Wagon get: org/slf4j/slf4j-api/maven-metadata.xml from #object[java.io.File 0x2da2c40 /home/alexj/.m2/repository/org/slf4j/slf4j-api/maven-metadata-jcenter.xml.part]                                       
HTTP Wagon get: org/slf4j/slf4j-api/maven-metadata.xml.sha1 from #object[java.io.File 0x1e4b5598 /home/alexj/.m2/repository/org/slf4j/slf4j-api/maven-metadata-jcenter.xml.sha1-434d733a8238037027019246643.tmp] 
```

**Comment by WhittlesJr** [comment]
For now I've submitted an issue against BACnet4J

https://github.com/infiniteautomation/BACnet4J/issues/22

**Comment by Frozenlock** [comment]
Should be fixed with https://github.com/Frozenlock/bacure/commit/573b99324d3d02003cbed530ced90cefaee71a71
