### ISSUE TITLE
Is the BACnet4J fork still needed?

### ISSUE THREAD

**Issue by WhittlesJr** [Frozenlock/bacure#28]
In project.clj, you have this note:

```
;; we use a fork of bacnet4j until https://github.com/infiniteautomation/BACnet4J/issues/23 is fixed
```

It looks like that issue is fixed. Do you still need to source your dependency from this fork, or can you use an official BACnet4J release?

**Comment by Frozenlock** [comment]
As the fix was merged I'm pretty sure we can use the official BACnet4J release without issues.
However `6.0.0` is a snapshot. I'd wait for a full release before updating `project.clj`.

**Comment by WhittlesJr** [comment]
Tracking this here:

https://github.com/infiniteautomation/BACnet4J/issues/48

**Comment by WhittlesJr** [comment]
Ah, looks like you can update to 5.0.2 if you use `com.infiniteautomation/bacnet4j`. The coordinates changed in 5.0.
