### ISSUE TITLE
Dependency resolution error

### ISSUE THREAD

**Issue by WhittlesJr** [Frozenlock/bacure#29]
As of `1.1.X`, I seemingly can't use bacure as a dependency:

```
Error building classpath. Unable to resolve lohbihler/sero-scheduler version: [1.0.0,2)
```

It does work on `1.0.8` though. Do you just need to roll back `sero-scheduler` to `1.0.0`?

**Comment by Frozenlock** [comment]
Please re-open if this is still an issue.
